# Generated by Django 2.0.4 on 2018-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
