# Generated by Django 2.0.4 on 2018-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_artist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
